when:
    - event: push
      branch: main

labels:
    platform: linux/amd64
    backend: docker

clone:
    git:
        image: woodpeckerci/plugin-git
        settings:
            partial: false

steps:
    github_mirror:
        image: alpine:latest
        environment:
            GITHUB_SSH_KEY:
                from_secret: github_ssh_key
        commands:
            - apk --no-cache update -q
            - apk --no-cache add git openssh
            - mkdir -pv $HOME/.ssh
            - ssh-keyscan -H -t rsa github.com >> ~/.ssh/known_hosts
            - echo "$GITHUB_SSH_KEY" > "$HOME/.ssh/id_rsa" && chmod 0600 $HOME/.ssh/id_rsa
            - git remote add github_origin git@github.com:notgull/smol-axum.git
            - git push github_origin main
